# This file was generated by GoReleaser. DO NOT EDIT.
cask "mtracer" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "a877603d47cc95067ec6e4bd13257b9779e37e0e302f6d0bf6460cab4b7c9029"
      url "https://github.com/mtracer-project/mtracer/releases/download/v#{version}/mtracer_#{version}_Darwin_x86_64.zip",
        verified: "github.com/mtracer-project/mtracer",
        cookies: {
          "license" => "accept-backup",
        }
    end
    on_arm do
      sha256 "73a17cd0189e30ce6e56f9785a0f4d3595584475d604e7ba0272d1ea707d44fc"
      url "https://github.com/mtracer-project/mtracer/releases/download/v#{version}/mtracer_#{version}_Darwin_arm64.zip",
        verified: "github.com/mtracer-project/mtracer",
        cookies: {
          "license" => "accept-backup",
        }
    end
  end

  name "mtracer"
  desc "mtracer is a CLI tool designed to facilitate testing through trace validation with tracing functionalities on distributed systems, released in version v0.2.0."
  homepage "https://github.com/mtracer-project/mtracer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mtracer"
  manpage "man/mtracer-check.1"
  manpage "man/mtracer-completion-bash.1"
  manpage "man/mtracer-completion-fish.1"
  manpage "man/mtracer-completion-powershell.1"
  manpage "man/mtracer-completion-zsh.1"
  manpage "man/mtracer-completion.1"
  manpage "man/mtracer-create.1"
  manpage "man/mtracer-run.1"
  manpage "man/mtracer.1"

  generate_completions_from_executable "bin/mtracer", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required

  caveats <<~EOS
    🚀 Let's trace!
  EOS
end
