# This file was generated by GoReleaser. DO NOT EDIT.
cask "mtracer" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "6b04dc7ea93eb651cfb77518889e4cea543dd4913d6dfbc0dc672753ef16dd89"
      url "https://github.com/mtracer-project/mtracer/releases/download/v#{version}/mtracer_#{version}_Darwin_x86_64.zip",
        verified: "github.com/mtracer-project/mtracer",
        cookies: {
          "license" => "accept-backup",
        }
    end
    on_arm do
      sha256 "bfd6bd75fb26d85ba40124c584add1796d6b3571015a3bd64130c53f47daa068"
      url "https://github.com/mtracer-project/mtracer/releases/download/v#{version}/mtracer_#{version}_Darwin_arm64.zip",
        verified: "github.com/mtracer-project/mtracer",
        cookies: {
          "license" => "accept-backup",
        }
    end
  end

  on_linux do
    on_intel do
      sha256 "2ace6a7e977e6645d991ae14e4d0e224435d840e768c1de4e209c6c5517b8329"
      url "https://github.com/mtracer-project/mtracer/releases/download/v#{version}/mtracer_#{version}_Linux_x86_64.tar.zst",
        verified: "github.com/mtracer-project/mtracer",
        cookies: {
          "license" => "accept-backup",
        }
    end
    on_arm do
      sha256 "91e9323130f6436612ae732b7604c319781bd3cca34c679b437de5200505a884"
      url "https://github.com/mtracer-project/mtracer/releases/download/v#{version}/mtracer_#{version}_Linux_arm64.tar.zst",
        verified: "github.com/mtracer-project/mtracer",
        cookies: {
          "license" => "accept-backup",
        }
    end
  end

  name "mtracer"
  desc "mtracer is a CLI tool designed to facilitate testing through trace validation with tracing functionalities on distributed systems, released in version v0.2.1."
  homepage "https://github.com/mtracer-project/mtracer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mtracer"
  manpage "man/mtracer-check.1"
  manpage "man/mtracer-create.1"
  manpage "man/mtracer-run.1"
  manpage "man/mtracer.1"

  generate_completions_from_executable "bin/mtracer", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required

  caveats <<~EOS
    🚀 Let's trace!
  EOS
end
