# This file was generated by GoReleaser. DO NOT EDIT.
cask "mtrace" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "a0bb735d909d9bafa1045946a64b65e5b2566f63968373429aa9e1033f0de70b"
      url "https://github.com/mtrace-project/mtrace/releases/download/v#{version}/mtrace_#{version}_Darwin_x86_64.zip",
        verified: "github.com/mtrace-project/mtrace",
        cookies: {
          "license" => "accept-backup",
        }
    end
    on_arm do
      sha256 "648cb42ce86cb4bb3ce1ed273bca85081c29a48aed6838f42ca9f5983c684be3"
      url "https://github.com/mtrace-project/mtrace/releases/download/v#{version}/mtrace_#{version}_Darwin_arm64.zip",
        verified: "github.com/mtrace-project/mtrace",
        cookies: {
          "license" => "accept-backup",
        }
    end
  end

  name "mtrace"
  desc "mtrace is a CLI tool designed to facilitate testing through trace validation with tracing functionalities on distributed systems, released in version v0.1.2."
  homepage "https://github.com/mtrace-project/mtrace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mtrace"
  manpage "man/mtrace-check.1"
  manpage "man/mtrace-completion-bash.1"
  manpage "man/mtrace-completion-fish.1"
  manpage "man/mtrace-completion-powershell.1"
  manpage "man/mtrace-completion-zsh.1"
  manpage "man/mtrace-completion.1"
  manpage "man/mtrace-create.1"
  manpage "man/mtrace-run.1"
  manpage "man/mtrace.1"

  generate_completions_from_executable "bin/mtrace", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required

  caveats <<~EOS
    🚀 Let's trace!
  EOS
end
