# This file was generated by GoReleaser. DO NOT EDIT.
cask "mtrace" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "f155099d4a335eb198009a656872342a53afd278259dce617a77431cbffb38ff"
      url "https://github.com/mtrace-project/mtrace/releases/download/v#{version}/mtrace_#{version}_Darwin_x86_64.zip",
        verified: "github.com/mtrace-project/mtrace",
        cookies: {
          "license" => "accept-backup",
        }
    end
    on_arm do
      sha256 "a2057b51fcc153ba8aac62a41b62705d6cbc7501fbbc6d2c54bf9761d06ebaaf"
      url "https://github.com/mtrace-project/mtrace/releases/download/v#{version}/mtrace_#{version}_Darwin_arm64.zip",
        verified: "github.com/mtrace-project/mtrace",
        cookies: {
          "license" => "accept-backup",
        }
    end
  end

  name "mtrace"
  desc "mtrace is a CLI tool designed to facilitate testing through trace validation with tracing functionalities on distributed systems, released in version v0.1.1."
  homepage "https://github.com/mtrace-project/mtrace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mtrace"
  manpage "man/mtrace-check.1"
  manpage "man/mtrace-create.1"
  manpage "man/mtrace-run.1"
  manpage "man/mtrace.1"

  generate_completions_from_executable "bin/mtrace", "completions",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required

  caveats <<~EOS
    🚀 Let's trace!
  EOS
end
